#Momin Rifat
"""
Django settings for E_shop project.
Siyam
mahathir mohammad SIyam


Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Moved out of source control. Falls back to the old dev key locally,
# but on Render set a SECRET_KEY environment variable in the dashboard.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-5xmhvawk$%-+rreht6#_t&f0fu)+@ytj=*vtxiey65+5g0_*$x'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Cloudinary — must come before your own apps so the storage
    # backend is registered before anything tries to use it.
    'cloudinary_storage',
    'cloudinary',

    'app.apps.AppConfig',
    'cart',


]
CART_SESSION_ID= 'cart'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'ECommerce.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                 'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processor.cart_total_amount',
                'app.social_context_processor.social_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'ECommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Where collectstatic will collect files for deployment
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional folders for dev
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# ── Media files (user-uploaded product photos, etc.) ──────────────
# MEDIA_URL/MEDIA_ROOT were missing before — that alone made uploads
# 404 with no settings to tell Django where to save or serve them.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Cloudinary credentials ─────────────────────────────────────────
# Get these from your Cloudinary dashboard, then set them as
# environment variables in Render (Settings → Environment), NOT here.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# ── Storage backends (Django 5+/6 style) ───────────────────────────
# default  -> all FileField/ImageField uploads go to Cloudinary,
#             so they survive Render restarts/redeploys.
# staticfiles -> unchanged, still served locally via WhiteNoise.
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'

# Source - https://stackoverflow.com/a/6367458
# Posted by Jordan, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-05, License - CC BY-SA 3.0

# ── Email ────────────────────────────────────────────────────────
# Password moved out of source control. Set EMAIL_HOST_PASSWORD as an
# environment variable in Render. IMPORTANT: change your Gmail password
# now if it was ever committed to Git or shared anywhere with the old
# plaintext value — treat it as compromised.
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '24101194@uap-bd.edu')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')


LOGIN_REDIRECT_URL='index'
LOGOUT_REDIRECT_URL='index'
LOGIN_URL = '/accounts/login/'