# Momin Rifat
"""
Django settings for E_shop project.

Siyam
Mahathir Mohammad Siyam

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = BASE_DIR / "static"

# Load .env file for local development
load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-5xmhvawk$%-+rreht6#_t&f0fu)+@ytj=*vtxiey65+5g0_*$x"
)

# CHANGED: matches the portfolio project's pattern — DEBUG is read
# directly from an env var instead of inferred from Render's presence.
# You MUST set DEBUG=False explicitly in Render's environment variables
# for production; if you forget, this defaults to False anyway (safe),
# but that also means you must set DEBUG=True yourself for local dev
# if you rely on this var rather than always running locally without
# it set.
DEBUG = os.environ.get("DEBUG", "False") == "True"

# CHANGED: now env-driven like the portfolio project, instead of a
# hardcoded ".onrender.com" wildcard baked into the code. On Render,
# set ALLOWED_HOSTS="miyabi-website-7.onrender.com" (comma-separate
# multiple hosts if needed). Falls back to "*" if unset, which accepts
# any Host header — fine for quick testing, but set the real env var
# before going live for real.
ALLOWED_HOSTS = (
    os.environ.get("ALLOWED_HOSTS", "").split(",")
    if os.environ.get("ALLOWED_HOSTS")
    else ["*"]
)

# Safety net: if Render's own RENDER_EXTERNAL_HOSTNAME is available,
# append it automatically so you can't lock yourself out just by
# forgetting to set ALLOWED_HOSTS manually.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# CHANGED: now env-driven like the portfolio project. On Render, set
# CSRF_TRUSTED_ORIGINS="https://miyabi-website-7.onrender.com" —
# without this set correctly, every POST request (login, checkout,
# admin) fails with a 403 once DEBUG is False.
CSRF_TRUSTED_ORIGINS = (
    os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if os.environ.get("CSRF_TRUSTED_ORIGINS")
    else []
)

# Safety net: auto-add an origin for Render's own external hostname so
# admin/login/checkout don't silently 403 if you forget to set the
# env var above.
if RENDER_EXTERNAL_HOSTNAME:
    auto_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if auto_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(auto_origin)


# ============================================================
# HTTPS / RENDER PROXY
# ============================================================

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Cloudinary — must come before your own apps
    "cloudinary_storage",
    "cloudinary",

    # Your apps
    "app.apps.AppConfig",
    "cart",
]


# Cart session
CART_SESSION_ID = "cart"


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise — must be right after SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "ECommerce.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [

                "django.template.context_processors.debug",
                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                # Cart
                "cart.context_processor.cart_total_amount",

                # Social links
                "app.social_context_processor.social_links",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "ECommerce.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

# CHANGED: matches the portfolio project's pattern — dj_database_url
# reads DATABASE_URL (your Render Postgres instance) when set, and
# falls back to a plain local sqlite file otherwise. This REPLACES the
# earlier /var/data/db.sqlite3 approach, which only works with a paid
# Render persistent disk and was the leading suspect behind your 500
# error (the /var/data directory doesn't exist without one).
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

# Where collectstatic collects files for deployment
STATIC_ROOT = BASE_DIR / "staticfiles"

# CHANGED: matches the portfolio project's pattern — only include the
# dev static folder if it actually exists, otherwise collectstatic can
# raise an error on Render if the folder was never committed.
STATICFILES_DIRS = [STATIC_DIR] if STATIC_DIR.is_dir() else []


# ============================================================
# MEDIA FILES
# ============================================================
# NOTE: unlike the portfolio project, Miyabi keeps MEDIA_URL/MEDIA_ROOT
# and Cloudinary below — product images and reel videos are uploaded
# through the admin, so they need somewhere durable to live. The
# portfolio project has no user uploads, so it skips this section
# entirely; Miyabi can't skip it without losing every uploaded image
# on the next deploy.

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# CLOUDINARY  (credentials loaded from .env locally, from Render's
# environment variables in production — same three keys either way)
# ============================================================

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME", ""),
    "API_KEY":    os.environ.get("CLOUDINARY_API_KEY", ""),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET", ""),
}


# ============================================================
# STORAGE BACKENDS
# ─────────────────────────────────────────────────────────────
# NOTE: the portfolio project uses a single flat STATICFILES_STORAGE
# setting (the older, deprecated style) always pointed at WhiteNoise's
# compressed storage, even in local dev. Miyabi keeps the newer
# STORAGES dict instead, since it's the current Django pattern and
# lets static/media storage differ between dev and production:
#
#   DEBUG == True  (local machine):
#     - media  -> local filesystem, saved under MEDIA_ROOT
#     - static -> plain StaticFilesStorage (easier to debug missing
#                 files, like the earlier Font Awesome path issue)
#
#   DEBUG == False (production / Render):
#     - media  -> Cloudinary, so uploads persist across deploys
#     - static -> WhiteNoise's compressed, hashed storage
# ============================================================

STORAGES = {

    "default": {
        "BACKEND": (
            "django.core.files.storage.FileSystemStorage"
            if DEBUG else
            "cloudinary_storage.storage.MediaCloudinaryStorage"
        ),
    },

    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG else
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}


# ============================================================
# SECURITY HARDENING (only active when DEBUG is False)
# ============================================================
# ADDED: ported from the portfolio project — Miyabi didn't have this
# before. Without these, cookies could still be sent over plain HTTP
# even though the site is actually served over HTTPS via Render.

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# ============================================================
# LOGGING
# ============================================================
# Django's default logging only prints to console when DEBUG=True.
# With DEBUG=False (production), unhandled exceptions were being
# silently swallowed — the access log showed "500" with no traceback
# anywhere. This forces errors to always print to stdout, which
# Render captures in its Logs tab regardless of DEBUG.

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# EMAIL
# ============================================================

EMAIL_USE_TLS = True

EMAIL_HOST = "smtp.gmail.com"

EMAIL_PORT = 587

EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    "24101194@uap-bd.edu"
)

EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")


# ============================================================
# LOGIN / LOGOUT
# ============================================================

LOGIN_REDIRECT_URL = "index"

LOGOUT_REDIRECT_URL = "index"

LOGIN_URL = "/accounts/login/"